### ISSUE TITLE
Update Emperor website

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2-emperor#109]
**Bug Description**
Because http://emperor.microbio.me/ is down for me right now.
Looks like `microbio.me` may now be down in favor of `microsetta.ucsd.edu`, which makes sense

Maybe we use https://knightlab.ucsd.edu/wordpress/?p=200 or just directly link the repo:  https://github.com/biocore/emperor

@ElDeveloper, are you still a good point of contact for Emperor? Can you recommend a website?

**Comment by ElDeveloper** [comment]
The GitHub pages website is the last site standing. Although I think it's a bit out of date. http://biocore.github.io/emperor/build/html/index.html


On Sep 26, 2024, at 6:57 AM, Colin J. Brislawn ***@***.***> wrote:



Bug Description
Because http://emperor.microbio.me/ is down for me right now.
Looks like microbio.me may now be down in favor of microsetta.ucsd.edu, which makes sense

Maybe we use https://knightlab.ucsd.edu/wordpress/?p=200 or just directly link the repo: https://github.com/biocore/emperor

@ElDeveloper<https://github.com/ElDeveloper>, are you still a good point of contact for Emperor? Can you recommend a website?
