### ISSUE TITLE
add biplot support

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-emperor#26]
This came up on the forum [here](https://forum.qiime2.org/t/processing-questions-visualizations-and-taxonomy-assignment/146).

**Comment by ElDeveloper** [comment]
We are working on this: https://github.com/biocore/emperor/pull/543

**Comment by jairideout** [comment]
Cool! I'll leave this issue open since we'll need to hook up biplot support to the plugin when it's available in Emperor.

**Comment by nbokulich** [comment]
another forum [xref](https://forum.qiime2.org/t/emperor-n-taxa-to-keep-beta-stats/2730)

in this case, specifically that biplot support include an `n_taxa_to_keep` parameter, similar to qiime1

**Comment by ElDeveloper** [comment]
I wanted to give everyone a heads up that I have put together the first prototype of biplots in the new version of Emperor, if you have any suggestions or feature requests, please refer them to this PR:
https://github.com/biocore/emperor/pull/646

Currently the only example available is found in a notebook in that PR, but if you have any questions, let me know and we can figure something out.

**Comment by ElDeveloper** [comment]
Another question would be to decide what biplot-generating methods should we include in QIIME2, RDA and PLS might be good ideas, but

**Comment by mortonjt** [comment]
Awesome!

On Mar 16, 2018 1:25 PM, "Yoshiki Vázquez Baeza" <notifications@github.com>
wrote:

Closed #26 <https://github.com/qiime2/q2-emperor/issues/26>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/qiime2/q2-emperor/issues/26#event-1526348884>, or mute
the thread

**Comment by ElDeveloper** [comment]
The current release of emperor now supports display of biplots. The main missing piece to this puzzle is that we don't have a method in QIIME2 to compute the biplots. @mortonjt helped me put together [this notebook](https://github.com/biocore/emperor/blob/new-api/examples/biplot.ipynb) with an implementation of compositional principal component analysis. I assume that the ideal case would be to put this in scikit-bio and then create a method in q2-diversity to call this method.

@gregcaporaso @ebolyen An alternative to what I mention above is to put the code from the notebook directly into q2-diversity, that way we could have the method sooner rather than later. Though I acknowledge this is not ideal.

**Comment by ebolyen** [comment]
It seems like scikit-bio is pretty well on its way to being "unstuck" as it were. Maybe this is an easy target to hit for a hypothetical June release?

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/core-diversity-analysis/4841)

**Comment by ElDeveloper** [comment]
🥇
